### ISSUE TITLE
[FEATURE] Is it possible to render standard formiojs components aside material components?

### ISSUE THREAD

**Issue by JoeyHengst** [formio/angular-material-formio#1]
Is it possible to render standard formiojs components aside the custom "material components"? 

So for example for the TextField instead of using the angular material component I would just like to use:

 ```
// import { TextFieldComponent } from './textfield/textfield.component';
import TextFieldComponent from 'formiojs/components/textfield/TextField';
```

**Comment by travist** [comment]
In this case, you don't need to use the angular-material-formio library. Just use angular-formio.

**Comment by JoeyHengst** [comment]
Ah sorry I need to clarify some more. 

We want to use the same structure you did in this package but instead of using angular material we want to use our own design system.

So using the same structure in this package but without material is it possible to use the standard components from formio?

The reason I am asking this is because if formio releases a new standard component we would like to use that component instead of making a "custom component" to use our design. 

Is this possible? Thank you.
