### ISSUE TITLE
is it possible to use file upload in angular-formio ? [BUG] 

### ISSUE THREAD

**Issue by Aswany09** [formio/angular-material-formio#153]
is it possible to use file upload in angular-formio?

- Hosting type
  - [] Form.io
  - [x] Local deployment
    - Version: 1.11.0
- Frontend framework: Angular Material
- Browser: Chrome,Firefox
- Browser version: 70+

## Steps to Reproduce
1. add file upload to formbuilder
2. formrender doesn't show file input (Unknown Component: File)
 
 

## Example
![image](https://user-images.githubusercontent.com/43567795/95752105-d488ca80-0c9f-11eb-8403-0dcd7bd548f7.png)
 

form JSON,

{"components": [
        {
            "label": "Upload",
            "tableView": false,
            "storage": "base64",
            "webcam": false,
            "fileTypes": [
                {
                    "label": "",
                    "value": ""
                }
            ],
            "key": "upload",
            "type": "file",
            "input": true
        },
        {
            "label": "Text Field",
            "tableView": true,
            "key": "textField",
            "type": "textfield",
            "input": true
        }
]}

**Comment by wag110894** [comment]
Hello @Aswany09, 

The file component is part of our premium components and you will need to have access in order to use our file upload component as well as many others.

Please let me know if you are interested and we can get the process started.
