### ISSUE TITLE
[BUG] DayComponent Wizard view throws error

### ISSUE THREAD

**Issue by joennlae** [formio/angular-material-formio#19]
First of all: **Thanks for your effort to implement wizard display for angular material.** 

## Environment
Please provide as many details as you can:
- Anuglar-Material-Formio version: 1.4.0
- Formio.js version: 4.0.9
- Frontend framework: Angular

## Steps to Reproduce
1. 
```html
<mat-formio [form]="{
    display: 'wizard',
    components: [
         {
             type: 'day',
             label: '',
             key: 'day'
         }
   ]
}" ></mat-formio>
```

## Expected behavior
Should no throw an error. An behave like it does when rendering as a form instead of a wizard.

```html
<mat-formio [form]="{
    display: 'form',
    components: [
         {
             type: 'day',
             label: '',
             key: 'day'
         }
   ]
}" ></mat-formio>
````

## Observed behavior
When rendering as a wizard it throws the error:
``` TypeError: Cannot read property 'value' of undefined ```
on this line:
https://github.com/formio/angular-material-formio/blob/497b117dd56edf3148cb626c83f4ebca580fd5fb/projects/angular-material-formio/src/lib/components/day/day.component.ts#L6

Thank you for looking into it.

**Comment by travist** [comment]
Thanks for this... we will take a look.

**Comment by joennlae** [comment]
Just to keep this thread relevant. I know that you did not focus on that. 
The issues still exists in v1.6.3.

**Comment by travist** [comment]
@vlad-shusterman do you mind adding some variable protection around this line? Shouldn't take long.

**Comment by vlad-shusterman** [comment]
@travist I'll do it.

**Comment by joennlae** [comment]
@travist @vlad-shusterman Thank you for solving it.
