### ISSUE TITLE
not able to build angular material form.io

### ISSUE THREAD

**Issue by LaksmiEzhil** [formio/angular-material-formio#20]
I am using angular material form.io using json.  When I try to build the app using ng build --prod, I am getting the below warning message. 

WARNING in ./node_modules/angular-material-formio/node_modules/formiojs/utils/utils.js

Also, material form.io not loading in server. please help.

**Comment by travist** [comment]
Does it provide you what the actual warning was? That would be helpful.

**Comment by LaksmiEzhil** [comment]
@travist, thanks for your immediate reply. This is the actual warning I am getting.

WARNING in ./node_modules/angular-material-formio/node_modules/formiojs/utils/utils.js
Module not found: Error: Can't resolve 'vm' in 'C:\dev\sevahealthWeb\node_modules\angular-material-formio\node_modules\formiojs\utils

**Comment by travist** [comment]
Ok... this is complaining about our Isomorphic validation...  we will take a look.

**Comment by LaksmiEzhil** [comment]
Thanks travist. I am waiting for good news.

**Comment by travist** [comment]
This is resolved in the 1.5.0 build.

**Comment by LaksmiEzhil** [comment]
Thanks travist. I will check.
